sudo: required #super user level permissions
services:
  - docker #We need a docker

before_install:
  - docker build -t arunreddy508/docker-react-demo -f Dockerfile.dev . #some series of steps that needs to occur before we deploy


script:
  - docker run arunreddy508/docker-react-demo npm run test -- --coverage  #The defaul behaviour of npm run test never exits that is why we are writing -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-demo"
  env: "DockerDemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-154242726126"
  bucket_path: "docker-demo"
  on:
    branch: master #Only the code from master branch gets deployed
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  #Generate Api keys that travis ci can use to communicated with travis ci
  